// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace HateSpeech
{
    public partial class GenderBias
    {
        /// <summary>
        /// model input class for GenderBias.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"comments")]
            public string Comments { get; set; }

            [ColumnName(@"contain_gender_bias")]
            public bool Contain_gender_bias { get; set; }

            [ColumnName(@"bias")]
            public string Bias { get; set; }

            [ColumnName(@"hate")]
            public string Hate { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for GenderBias.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName("PredictedLabel")]
            public bool Prediction { get; set; }

            public float Score { get; set; }

            // The probability calculated by calibrating the score of having true as the label.
            public float Probability { get; set; }
        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("GenderBias.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
